project:
  type: website
  output-dir: docs

website:
  title: "Julius Hoffman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: JuliusHoffman_Resume.pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

